version: "3.8"

services:
  ca:
    volumes:
      - cache:/cache

  memcached:
    restart: always

  redis:
    restart: always

  mariadb:
    restart: always

  git:
    restart: always
    volumes:
      - ${GIT_DATA_DIR}:/aurweb/aur.git
      - cache:/cache

  smartgit:
    restart: always
    volumes:
      - ${GIT_DATA_DIR}:/aurweb/aur.git
      - cache:/cache
      - smartgit_run:/var/run/smartgit

  cgit-php:
    restart: always
    volumes:
      - ${GIT_DATA_DIR}:/aurweb/aur.git

  cgit-fastapi:
    restart: always
    volumes:
      - ${GIT_DATA_DIR}:/aurweb/aur.git

  php-fpm:
    restart: always
    volumes:
      - cache:/cache

  fastapi:
    restart: always
    environment:
      - FASTAPI_BACKEND="gunicorn"
    volumes:
      - cache:/cache

  nginx:
    restart: always
    volumes:
      - ${GIT_DATA_DIR}:/aurweb/aur.git
      - cache:/cache
      - logs:/var/log/nginx
      - smartgit_run:/var/run/smartgit

volumes:
  mariadb_run: {} # Share /var/run/mysqld
  mariadb_data: {} # Share /var/lib/mysql
  git_data: {} # Share aurweb/aur.git
  smartgit_run: {}
  cache: {}
  logs: {}
