version: "3.8"

services:
  ca:
    volumes:
      - cache:/cache

  git:
    volumes:
      - git_data:/aurweb/aur.git
      - cache:/cache
      - ${MARIADB_SOCKET_DIR}:/var/run/mysqld

  smartgit:
    volumes:
      - git_data:/aurweb/aur.git
      - cache:/cache
      - smartgit_run:/var/run/smartgit

  php-fpm:
    volumes:
      - cache:/cache
      - ${MARIADB_SOCKET_DIR}:/var/run/mysqld

  fastapi:
    environment:
      - FASTAPI_BACKEND="gunicorn"
    volumes:
      - cache:/cache
      - ${MARIADB_SOCKET_DIR}:/var/run/mysqld

  mariadb_init:
    volumes:
      - ${MARIADB_SOCKET_DIR}:/var/run/mysqld

  nginx:
    volumes:
      - git_data:/aurweb/aur.git
      - cache:/cache
      - logs:/var/log/nginx
      - smartgit_run:/var/run/smartgit

volumes:
  mariadb_run: {} # Share /var/run/mysqld
  mariadb_data: {} # Share /var/lib/mysql
  git_data: {} # Share aurweb/aur.git
  smartgit_run: {}
  cache: {}
  logs: {}
