#
# Docker service definitions for the aurweb project.
#
# Notable services:
#   - `sharness` - Run sharness test suites
#   - `pytest-mysql` - Run pytest suites with MariaDB
#   - `pytest-sqlite` - Run pytest suites with SQLite
#   - `test` - Run sharness, pytest-mysql and pytest-sqlite
#   - `mariadb` - `port 13306` - MariaDB server for docker
#   - `ca` - Certificate Authority generation
#   - `git` - `port 2222` - Git over SSH server
#   - `fastapi` - hypercorn service for aurweb's FastAPI app
#   - `php-fpm` - Execution server for PHP aurweb
#   - `nginx` - `ports 8444 (FastAPI), 8443 (PHP)` - Everything
#     - You can reach `nginx` via FastAPI at `https://localhost:8444/`
#       or via PHP at `https://localhost:8443/`. CGit can be reached
#       via the `/cgit/` request uri on either server.
#
# Copyright (C) 2021 aurweb Development
# All Rights Reserved.
version: "3.8"

services:
  ca:
    build: .
    image: aurweb:latest
    init: true
    entrypoint: /docker/ca-entrypoint.sh
    command: echo

  memcached:
    build: .
    image: aurweb:latest
    init: true
    command: /docker/scripts/run-memcached.sh
    healthcheck:
      test: "bash /docker/health/memcached.sh"

  redis:
    build: .
    image: aurweb:latest
    init: true
    entrypoint: /docker/redis-entrypoint.sh
    command: /docker/scripts/run-redis.sh
    healthcheck:
      test: "bash /docker/health/redis.sh"
    ports:
      - "16379:6379"

  mariadb:
    build: .
    image: aurweb:latest
    init: true
    entrypoint: /docker/mariadb-entrypoint.sh
    command: /usr/bin/mysqld_safe --datadir=/var/lib/mysql
    ports:
      # This will expose mariadbd on 127.0.0.1:13306 in the host.
      # Ex: `mysql -uaur -paur -h 127.0.0.1 -P 13306 aurweb`
      - "13306:3306"
    volumes:
      - mariadb_run:/var/run/mysqld # Bind socket in this volume.
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: "bash /docker/health/mariadb.sh"

  mariadb_init:
    build: .
    image: aurweb:latest
    init: true
    environment:
      - DB_HOST=mariadb
    entrypoint: /docker/mariadb-init-entrypoint.sh
    command: echo "MariaDB tables initialized."
    depends_on:
      mariadb:
        condition: service_healthy

  git:
    build: .
    image: aurweb:latest
    init: true
    environment:
      - AUR_CONFIG=/aurweb/conf/config
      - DB_HOST=mariadb
    entrypoint: /docker/git-entrypoint.sh
    command: /docker/scripts/run-sshd.sh
    ports:
      - "2222:2222"
    healthcheck:
      test: "bash /docker/health/sshd.sh"
    depends_on:
      mariadb_init:
        condition: service_started

  smartgit:
    build: .
    image: aurweb:latest
    init: true
    environment:
      - AUR_CONFIG=/aurweb/conf/config
    entrypoint: /docker/smartgit-entrypoint.sh
    command: /docker/scripts/run-smartgit.sh
    healthcheck:
      test: "bash /docker/health/smartgit.sh"
    depends_on:
      mariadb:
        condition: service_healthy

  cgit-php:
    build: .
    image: aurweb:latest
    init: true
    environment:
      - AUR_CONFIG=/aurweb/conf/config
    entrypoint: /docker/cgit-entrypoint.sh
    command: /docker/scripts/run-cgit.sh 3000 "https://localhost:8443/cgit"
    healthcheck:
      test: "bash /docker/health/cgit.sh 3000"
    depends_on:
      git:
        condition: service_healthy
    volumes:
      - git_data:/aurweb/aur.git

  cgit-fastapi:
    build: .
    image: aurweb:latest
    init: true
    environment:
      - AUR_CONFIG=/aurweb/conf/config
    entrypoint: /docker/cgit-entrypoint.sh
    command: /docker/scripts/run-cgit.sh 3000 "https://localhost:8444/cgit"
    healthcheck:
      test: "bash /docker/health/cgit.sh 3000"
    depends_on:
      git:
        condition: service_healthy
    volumes:
      - git_data:/aurweb/aur.git

  php-fpm:
    build: .
    image: aurweb:latest
    init: true
    environment:
      - AUR_CONFIG=/aurweb/conf/config
      - DB_HOST=mariadb
    entrypoint: /docker/php-entrypoint.sh
    command: /docker/scripts/run-php.sh
    healthcheck:
      test: "bash /docker/health/php.sh"
    depends_on:
      ca:
        condition: service_started
      git:
        condition: service_healthy
      memcached:
        condition: service_healthy
    ports:
      - "19000:9000"

  fastapi:
    build: .
    image: aurweb:latest
    init: true
    environment:
      - AUR_CONFIG=conf/config
      - DB_HOST=mariadb
    entrypoint: /docker/fastapi-entrypoint.sh
    command: /docker/scripts/run-fastapi.sh "${FASTAPI_BACKEND}"
    healthcheck:
      test: "bash /docker/health/fastapi.sh ${FASTAPI_BACKEND}"
    depends_on:
      ca:
        condition: service_started
      git:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "18000:8000"

  nginx:
    build: .
    image: aurweb:latest
    init: true
    environment:
      - AUR_CONFIG=conf/config
    entrypoint: /docker/nginx-entrypoint.sh
    command: /docker/scripts/run-nginx.sh
    ports:
      - "8443:8443" # PHP
      - "8444:8444" # FastAPI
    healthcheck:
      test: "bash /docker/health/nginx.sh"
    depends_on:
      cgit-php:
        condition: service_healthy
      cgit-fastapi:
        condition: service_healthy
      smartgit:
        condition: service_healthy
      fastapi:
        condition: service_healthy
      php-fpm:
        condition: service_healthy

  sharness:
    build: .
    image: aurweb:latest
    profiles: ["dev"]
    init: true
    environment:
      - AUR_CONFIG=conf/config.sqlite
    entrypoint: /docker/test-sqlite-entrypoint.sh
    command: /docker/scripts/run-sharness.sh
    stdin_open: true
    tty: true
    depends_on:
      git:
        condition: service_healthy
    volumes:
      - git_data:/aurweb/aur.git
      - ./cache:/cache
      - ./aurweb:/aurweb/aurweb
      - ./migrations:/aurweb/migrations
      - ./test:/aurweb/test
      - ./web/html:/aurweb/web/html
      - ./web/template:/aurweb/web/template
      - ./web/lib:/aurweb/web/lib
      - ./templates:/aurweb/templates

  pytest-mysql:
    build: .
    image: aurweb:latest
    profiles: ["dev"]
    init: true
    environment:
      - AUR_CONFIG=conf/config
      - DB_HOST=mariadb
    entrypoint: /docker/test-mysql-entrypoint.sh
    command: /docker/scripts/run-pytests.sh clean
    stdin_open: true
    tty: true
    depends_on:
      mariadb_init:
        condition: service_started
    volumes:
      - git_data:/aurweb/aur.git
      - ./cache:/cache
      - ./aurweb:/aurweb/aurweb
      - ./migrations:/aurweb/migrations
      - ./test:/aurweb/test
      - ./web/html:/aurweb/web/html
      - ./web/template:/aurweb/web/template
      - ./web/lib:/aurweb/web/lib
      - ./templates:/aurweb/templates

  pytest-sqlite:
    build: .
    image: aurweb:latest
    profiles: ["dev"]
    init: true
    environment:
      - AUR_CONFIG=conf/config.sqlite
    entrypoint: /docker/test-sqlite-entrypoint.sh
    command: setup-sqlite.sh run-pytests.sh clean
    stdin_open: true
    tty: true
    volumes:
      - git_data:/aurweb/aur.git
      - ./cache:/cache
      - ./aurweb:/aurweb/aurweb
      - ./migrations:/aurweb/migrations
      - ./test:/aurweb/test
      - ./web/html:/aurweb/web/html
      - ./web/template:/aurweb/web/template
      - ./web/lib:/aurweb/web/lib
      - ./templates:/aurweb/templates

  test:
    build: .
    image: aurweb:latest
    profiles: ["dev"]
    init: true
    environment:
      - AUR_CONFIG=conf/config
      - DB_HOST=mariadb
    entrypoint: /docker/tests-entrypoint.sh
    command: setup-sqlite.sh run-tests.sh
    stdin_open: true
    tty: true
    depends_on:
      mariadb_init:
        condition: service_started
    volumes:
      - git_data:/aurweb/aur.git
      - ./cache:/cache
      - ./aurweb:/aurweb/aurweb
      - ./migrations:/aurweb/migrations
      - ./test:/aurweb/test
      - ./web/html:/aurweb/web/html
      - ./web/template:/aurweb/web/template
      - ./web/lib:/aurweb/web/lib
      - ./templates:/aurweb/templates

volumes:
  mariadb_run: {} # Share /var/run/mysqld/mysqld.sock
  mariadb_data: {} # Share /var/lib/mysql
  git_data: {} # Share aurweb/aur.git
  smartgit_run: {}
